name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run flake8 (lint)
        run: |
          source venv/bin/activate
          flake8 modern_phone_checker

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings

  docker-smoke-test:
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t modern-phone-checker:ci .

      - name: Run CLI smoke test
        run: docker run --rm modern-phone-checker:ci modern-phone-checker --help
